CRUD for daily entry
cse110-sp21-group13/cse110-sp21-group13 pull request #52
Opened 2021-05-12 20:12 UTC by zhl024

Currently, the read/daily cannot handle deletion of bullets on its end. It can only send the response that replaces bullet id with its corresponding Json object. It cannot handle cases like a bullet is deleted. Then it will cause a 404 error. One way to do this maybe to delete bullet in the bullet end: when delete a bullet, delete its id in daily too. Or we can just disable deleting bullets.

Other than that, create, delete, and update work as expected.

2021-05-12 20:15 UTC, b2wu commented on source/routes/update/daily.js
> +                };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                }
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/create/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/read/daily.js
> +    '/read/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/read/daily": {
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/update/daily.js
> +    '/update/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/update/daily": {
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/read/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/read/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/create/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/update/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/create/daily.js
> +    '/create/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/create/daily": {
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/update/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/create/daily.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["post"],
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/delete/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/delete/daily.js
> +    '/delete/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/delete/daily": {
```

2021-05-12 20:15 UTC, b2wu commented on source/routes/delete/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/read/daily.js
> +    '/read/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/read/daily": {
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/update/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/create/daily.js
> +                    throw new Error('MISSING FIELD');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                    throw new Error("MISSING FIELD");
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/read/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/read/daily.js
> +        methods: ['get'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["get"],
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/create/daily.js
> +            requiredFields.forEach((jsonField, index)=>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            requiredFields.forEach((jsonField, index) =>{
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/create/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/update/daily.js
> +                };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                }
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/read/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/read/daily.js
> +            .then(response => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            .then((response) => {
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/update/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/read/daily.js
> +                    .finally(()=>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                    .finally(() =>{
```

2021-05-13 01:22 UTC, b2wu commented on source/routes/create/daily.js
> +}
Codacy has a fix for the issue: [Missing semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
}; 
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/create/daily.js
> +            requiredFields.forEach((jsonField, index)=>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            requiredFields.forEach((jsonField, index) =>{
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/read/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/create/daily.js
> +                    throw new Error('MISSING FIELD');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                    throw new Error("MISSING FIELD");
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/delete/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/create/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/read/daily.js
> +    '/read/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/read/daily": {
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/read/daily.js
> +            .then(response => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            .then((response) => {
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/update/daily.js
> +                };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                }
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/read/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/create/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/update/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/create/daily.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["post"],
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/read/daily.js
> +                    .finally(()=>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                    .finally(() =>{
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/update/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/update/daily.js
> +    '/update/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/update/daily": {
```

2021-05-13 02:05 UTC, b2wu commented on source/routes/read/daily.js
> +        methods: ['get'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["get"],
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/create/daily.js
> +}
Codacy has a fix for the issue: [Missing semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
}; 
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/read/daily.js
> +        methods: ['get'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["get"],
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/create/daily.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["post"],
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/read/daily.js
> +                    .finally(()=>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                    .finally(() =>{
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/delete/daily.js
> +    '/delete/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/delete/daily": {
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/read/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/delete/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/create/daily.js
> +                    throw new Error('MISSING FIELD');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                    throw new Error("MISSING FIELD");
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/update/daily.js
> +                };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                }
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/update/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/delete/daily.js
> +        methods: ['delete'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["delete"],
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/delete/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/read/daily.js
> +            .then(response => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            .then((response) => {
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/create/daily.js
> +    '/create/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/create/daily": {
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/update/daily.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["post"],
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/update/daily.js
> +    '/update/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/update/daily": {
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/update/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 03:58 UTC, b2wu commented on source/routes/create/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 04:08 UTC, dino-inc commented on source/package-lock.json
>  {
Probably want to remove this from the pull request, as it might cause merge issues.

2021-05-13 04:08 UTC, dino-inc commented on source/package.json
> -  "devDependencies": {},
This might also cause merge issues, though I'm not sure.

2021-05-13 04:10 UTC, dino-inc commented on source/routes/create/daily.js
> +            let requiredFields = ["user", "date", "docType", "monthKey", "bullets"];
Potentially switch the order around to reflect bullets being before monthKey in the assigning - ultimately trivial.

2021-05-13 04:15 UTC, dino-inc requested changes
A few error messages return more than just "error", which is inconsistent and should be replaced by just the word "error".

2021-05-13 04:15 UTC, dino-inc commented on source/routes/delete/daily.js
> +                        res.send("error caused by cannot get bullet Json by id");
I don't think we ever send anything more than 'error', so this would be inconsistent.

2021-05-13 04:15 UTC, dino-inc commented on source/routes/update/daily.js
> +                res.send("error caused by cannot find daily entry by id");
This should be changed to just "error" for consistency.

2021-05-13 04:15 UTC, dino-inc commented on source/routes/update/daily.js
> +                    res.send("error caused by cannot update DB");
This should be changed to just "error" for consistency.

2021-05-13 17:12 UTC, dino-inc requested changes
One of the routes will not send an error message if it errors, and an error message was left as a longer string.

2021-05-13 17:12 UTC, dino-inc commented on source/routes/read/daily.js
> +                console.log(err);
I just noticed - this doesn't send back an error message if it errors out.

2021-05-13 17:16 UTC, b2wu commented on source/routes/create/daily.js
> +    '/create/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/create/daily": {
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/delete/daily.js
> +    '/delete/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/delete/daily": {
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/read/daily.js
> +    '/read/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/read/daily": {
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/create/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/update/daily.js
> +    '/update/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    "/update/daily": {
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/read/daily.js
> +        methods: ['get'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["get"],
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/update/daily.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["post"],
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/delete/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/update/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/update/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 17:16 UTC, b2wu commented on source/routes/update/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 17:17 UTC, b2wu commented on source/routes/read/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 17:17 UTC, b2wu commented on source/routes/create/daily.js
> +            requiredFields.forEach((jsonField, index)=>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            requiredFields.forEach((jsonField, index) =>{
```

2021-05-13 17:17 UTC, b2wu commented on source/routes/read/daily.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 17:17 UTC, b2wu commented on source/routes/delete/daily.js
> +        methods: ['delete'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        methods: ["delete"],
```

2021-05-13 17:17 UTC, b2wu commented on source/routes/read/daily.js
> +            .then(response => {
Codacy has a fix for the issue: [Expected parentheses around arrow function argument.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            .then((response) => {
```

2021-05-13 17:17 UTC, b2wu commented on source/routes/delete/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 18:13 UTC, dino-inc approved these changes
Outside of potential issues merging due to package-lock, it appears to be good.

2021-05-14 17:19 UTC, merged

2021-05-14 17:22 UTC, b2wu commented on source/routes/update/daily.js
> +                    res.send("error");
Codacy has a fix for the issue: [Expected indentation of 18 spaces but found 20.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                  res.send("error");
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/update/daily.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Expected indentation of 4 spaces but found 8.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    methods: ['post'],
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/delete/daily.js
> +                response.bullets.forEach((bullet, index) => {
Codacy has a fix for the issue: [Expected indentation of 12 spaces but found 16.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            response.bullets.forEach((bullet, index) => {
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/update/daily.js
> +                        throw new Error("INVALID FIELD SPECIFIED");
Codacy has a fix for the issue: [Strings must use singlequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                        throw new Error('INVALID FIELD SPECIFIED');
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/update/daily.js
> +    '/update/daily': {
Codacy has a fix for the issue: [Expected indentation of 2 spaces but found 4.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
  '/update/daily': {
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/delete/daily.js
> +                        //delete bullet document
Codacy has a fix for the issue: [Expected space or tab after '//' in comment.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                        // delete bullet document
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/delete/daily.js
> +                //delete daily entry
Codacy has a fix for the issue: [Expected space or tab after '//' in comment.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                // delete daily entry
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/read/daily.js
> +                        res.send("error");
Codacy has a fix for the issue: [Expected indentation of 20 spaces but found 24.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                    res.send("error");
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/read/daily.js
> +            .then(response => {
Codacy has a fix for the issue: [Expected indentation of 10 spaces but found 12.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
          .then(response => {
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/read/daily.js
> +                        curr++;
Codacy has a fix for the issue: [Trailing spaces not allowed.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                        curr++;
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/delete/daily.js
> +                res.send("success");
Codacy has a fix for the issue: [Strings must use singlequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                res.send('success');
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/read/daily.js
> +            let tempArr = [];
Codacy has a fix for the issue: [Expected indentation of 6 spaces but found 12.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
      let tempArr = [];
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/create/daily.js
> +                if(!req.body[jsonField]){
Codacy has a fix for the issue: [Expected indentation of 8 spaces but found 16.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
        if(!req.body[jsonField]){
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/create/daily.js
> +            let requiredFields = ["user", "date", "docType", "monthKey", "bullets"];
Codacy has a fix for the issue: [Expected indentation of 6 spaces but found 12.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
      let requiredFields = ["user", "date", "docType", "monthKey", "bullets"];
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/create/daily.js
> +                res.send("error");
Codacy has a fix for the issue: [Strings must use singlequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                res.send('error');
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/create/daily.js
> +            })
Codacy has a fix for the issue: [Expected indentation of 6 spaces but found 12.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
      })
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/update/daily.js
> +                    }
Codacy has a fix for the issue: [Closing curly brace does not appear on the same line as the subsequent block.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                    } else{
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/read/daily.js
> +                let curr = 0;
Codacy has a fix for the issue: [Expected indentation of 12 spaces but found 16.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
            let curr = 0;
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/create/daily.js
> +                if(!req.body[jsonField]){
Codacy has a fix for the issue: [Expected space(s) after "if".](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                if (!req.body[jsonField]){
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/create/daily.js
> +    '/create/daily': {
Codacy has a fix for the issue: [Expected indentation of 2 spaces but found 4.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
  '/create/daily': {
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/delete/daily.js
> +                    });
Codacy has a fix for the issue: [Expected indentation of 18 spaces but found 20.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
                  });
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/read/daily.js
> +        methods: ['get'],
Codacy has a fix for the issue: [Expected indentation of 4 spaces but found 8.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    methods: ['get'],
```

2021-05-14 17:22 UTC, b2wu commented on source/routes/delete/daily.js
> +        methods: ['delete'],
Codacy has a fix for the issue: [Expected indentation of 4 spaces but found 8.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7422202)
```suggestion
    methods: ['delete'],
```