REST API for Month
cse110-sp21-group13/cse110-sp21-group13 pull request #54
Opened 2021-05-13 03:52 UTC by zhl024

All features work fine. But read/month currently is too redundant. Need optimization later.

2021-05-13 03:54 UTC, b2wu commented on source/routes/delete/month.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 03:54 UTC, b2wu commented on source/routes/read/bullet.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 03:54 UTC, b2wu commented on source/routes/create/month.js
> +    '/create/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/create/month": {
```

2021-05-13 03:54 UTC, b2wu commented on source/routes/update/daily.js
> +    '/update/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/update/daily": {
```

2021-05-13 03:54 UTC, b2wu commented on source/routes/create/bullet.js
> +    '/create/bullet': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/create/bullet": {
```

2021-05-13 03:54 UTC, b2wu commented on source/routes/update/month.js
> +                };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                }
```

2021-05-13 03:54 UTC, b2wu commented on source/routes/read/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 03:54 UTC, b2wu commented on source/routes/create/daily.js
> +    '/create/daily': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/create/daily": {
```

2021-05-13 03:55 UTC, b2wu commented on source/routes/create/bullet.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
        methods: ["post"],
```

2021-05-13 03:55 UTC, b2wu commented on source/routes/create/daily.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 03:55 UTC, b2wu commented on source/routes/delete/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 03:55 UTC, b2wu commented on source/routes/create/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 03:55 UTC, b2wu commented on source/routes/read/month.js
> +                    fields: ['user']
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                    fields: ["user"]
```

2021-05-13 03:55 UTC, b2wu commented on source/routes/create/daily.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 04:27 UTC, dino-inc requested changes
A bunch of unrelated files were included - did you rebase, or just accidentally commit the test files?

2021-05-13 04:27 UTC, dino-inc commented on admin/meetings/051221-sprint1check.md
> +# Meeting Note for 05/12/2021
This should not be in the Months story.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/create/bullet.js
> +const PouchDB = require('pouchdb');
This is from my bullet CRUD - it should definitely not be in this story and should be removed entirely.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/create/daily.js
> +const PouchDB = require('pouchdb');
This is from daily CRUD - also should be removed, as it will be committed in the daily pull request.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/delete/bullet.js
> +const PouchDB = require('pouchdb');
Similarly from my bullet CRUD, it must be removed before this can be approved.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/delete/daily.js
> +const PouchDB = require('pouchdb');
This is from your daily CRUD, should definitely not be in here and should be removed.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/delete/month.js
> +                        res.send("error caused by cannot get bullet Json by id");
For consistency, should return only "error".

2021-05-13 04:27 UTC, dino-inc commented on source/routes/delete/month.js
> +                res.send("delete success");
I believe this should also only return "success" - you know when you have sent a delete request, so it is unnecessary to inform the request sender of that.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/read/bullet.js
> +const PouchDB = require('pouchdb');
Also from bullet CRUD, should be removed before this can be merged.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/read/daily.js
> +const PouchDB = require('pouchdb');
From daily CRUD, should be removed before this can be merged.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/read/daily_optimization.js
> +const PouchDB = require('pouchdb');
This file is entirely commented code - it shouldn't need to be committed.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/read/month.js
> +                res.send("error: cannot find month doc");
For consistency, change this to "error".

2021-05-13 04:27 UTC, dino-inc commented on source/routes/update/bullet.js
> +const PouchDB = require('pouchdb');
From bullet CRUD, please remove it before this can be merged.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/update/daily.js
> +const PouchDB = require('pouchdb');
From daily CRUD, please remove it before this can be merged.

2021-05-13 04:27 UTC, dino-inc commented on source/routes/update/month.js
> +                    res.send("error caused by cannot update DB");
For consistency, change this and the error below it to just "error".

2021-05-13 17:09 UTC, dino-inc requested changes
The error message in month should be changed to just "error", but otherwise everything is fine.

2021-05-13 17:14 UTC, dino-inc approved these changes
The routes appear to be functional and consistent.

2021-05-13 17:14 UTC, b2wu commented on source/routes/delete/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/create/month.js
> +}
Codacy has a fix for the issue: [Missing semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
}; 
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/update/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/update/month.js
> +                };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                }
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/update/month.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/read/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/create/month.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/delete/month.js
> +    '/delete/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/delete/month": {
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/delete/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/create/month.js
> +                    throw new Error('MISSING FIELD');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                    throw new Error("MISSING FIELD");
```

2021-05-13 17:14 UTC, b2wu commented on source/routes/delete/month.js
> +        methods: ['delete'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
        methods: ["delete"],
```

2021-05-13 17:24 UTC, b2wu commented on source/routes/read/month.js
> +                        fields: ['date', '_id']
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                        fields: ["date", '_id']
```

2021-05-13 17:24 UTC, b2wu commented on source/routes/delete/month.js
> +        methods: ['delete'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
        methods: ["delete"],
```

2021-05-13 17:24 UTC, b2wu commented on source/routes/create/month.js
> +}
Codacy has a fix for the issue: [Missing semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
}; 
```

2021-05-13 17:24 UTC, b2wu commented on source/routes/create/month.js
> +                    throw new Error('MISSING FIELD');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                    throw new Error("MISSING FIELD");
```

2021-05-13 17:24 UTC, b2wu commented on source/routes/read/month.js
> +                    fields: ['user']
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                    fields: ["user"]
```

2021-05-13 17:24 UTC, b2wu commented on source/routes/create/month.js
> +            requiredFields.forEach((jsonField, index)=>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
            requiredFields.forEach((jsonField, index) =>{
```

2021-05-13 17:24 UTC, b2wu commented on source/routes/create/month.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/read/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/read/month.js
> +    '/read/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/read/month": {
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/update/month.js
> +    '/update/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/update/month": {
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/read/month.js
> +        methods: ['get'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
        methods: ["get"],
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/create/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/read/month.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const db = new PouchDB("db");
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/create/month.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
        methods: ["post"],
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/delete/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/create/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-13 17:25 UTC, b2wu commented on source/routes/delete/month.js
> +    '/delete/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/delete/month": {
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/create/month.js
> +            requiredFields.forEach((jsonField, index) =>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
            requiredFields.forEach((jsonField, index) =>{
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/create/month.js
> +    '/create/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/create/month": {
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/update/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/update/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/read/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/read/month.js
> +                        fields: ["date", '_id']
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                        fields: ["date", "_id"]
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/read/month.js
> +                                fields: ['date', '_id']
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                        fields: ["date", '_id']
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/update/month.js
> +                };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                }
```

2021-05-14 18:43 UTC, b2wu commented on source/routes/delete/month.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const db = new PouchDB("db");
```

2021-05-14 18:54 UTC, b2wu commented on source/routes/update/month.js
> +        methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
        methods: ["post"],
```

2021-05-14 18:54 UTC, b2wu commented on source/routes/read/month.js
> +                                fields: ['date', '_id']
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                        fields: ["date", '_id']
```

2021-05-14 18:54 UTC, b2wu commented on source/routes/update/month.js
> +                };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                }
```

2021-05-14 18:54 UTC, b2wu commented on source/routes/read/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-14 18:54 UTC, b2wu commented on source/routes/update/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-14 18:54 UTC, b2wu commented on source/routes/create/month.js
> +    '/create/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/create/month": {
```

2021-05-14 18:54 UTC, b2wu commented on source/routes/delete/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-14 19:05 UTC, merged

2021-05-14 19:06 UTC, b2wu commented on source/routes/update/month.js
> +                  res.send('success');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                  res.send("success");
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/create/month.js
> +      const requiredFields = ['user', 'month', 'bullets'];
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
      const requiredFields = ["user", 'month', 'bullets'];
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/delete/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/update/month.js
> +            };
Codacy has a fix for the issue: [Unnecessary semicolon.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                }
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/read/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/update/month.js
> +  '/update/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/update/month": {
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/delete/month.js
> +  '/delete/month': {
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
    "/delete/month": {
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/update/month.js
> +                throw new Error('INVALID FIELD SPECIFIED');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                throw new Error("INVALID FIELD SPECIFIED");
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/create/month.js
> +    methods: ['post'],
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
        methods: ["post"],
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/create/month.js
> +const db = new PouchDB('db');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const db = new PouchDB("db");
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/update/month.js
> +PouchDB.plugin(require('pouchdb-find'));
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
PouchDB.plugin(require("pouchdb-find"));
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/read/month.js
> +        res.send('error');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
        res.send("error");
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/update/month.js
> +                  res.send('error');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
                  res.send("error");
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/create/month.js
> +      requiredFields.forEach((jsonField, index) =>{
Codacy has a fix for the issue: [Missing space before =>.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
            requiredFields.forEach((jsonField, index) =>{
```

2021-05-14 19:06 UTC, b2wu commented on source/routes/read/month.js
> +const PouchDB = require('pouchdb');
Codacy has a fix for the issue: [Strings must use doublequote.](https://app.codacy.com/gh/cse110-sp21-group13/cse110-sp21-group13/pullRequest?prid=7423478)
```suggestion
const PouchDB = require("pouchdb");
```